In [22]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

data = {
    "City": ["Delhi", "Mumbai", np.nan, "Chennai", "Delhi"],
    "Age": [25, np.nan, 30, 35, 40],
    "Salary": [50000, 60000, 55000, np.nan, 65000]
}

df = pd.DataFrame(data)
print(df)

      City   Age   Salary
0    Delhi  25.0  50000.0
1   Mumbai   NaN  60000.0
2      NaN  30.0  55000.0
3  Chennai  35.0      NaN
4    Delhi  40.0  65000.0


###Using Pandas

In [23]:

num_imputer = SimpleImputer(strategy="mean")

df["Age"] = num_imputer.fit_transform(df[["Age"]])
df["Salary"] = num_imputer.fit_transform(df[["Salary"]])

In [24]:
cat_imputer = SimpleImputer(strategy="most_frequent")

df["City"] = cat_imputer.fit_transform(df[["City"]])[:, 0]

###Using SkLearn

In [3]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="constant", fill_value="Unknown")

df_imputed = imputer.fit_transform(df)

df_imputed = pd.DataFrame(df_imputed, columns=df.columns)

print(df_imputed)

      City   Gender
0    Delhi     Male
1   Mumbai  Unknown
2  Unknown   Female
3  Chennai     Male
4  Unknown  Unknown


In [26]:
encoder = OneHotEncoder( handle_unknown="ignore",
    sparse_output=False)

encoded = encoder.fit_transform(df[["City"]])

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(["City"])
)

df_final = pd.concat([df.drop("City", axis=1), encoded_df], axis=1)

print(df_final)

    Age   Salary  City_Chennai  City_Delhi  City_Mumbai
0  25.0  50000.0           0.0         1.0          0.0
1  32.5  60000.0           0.0         0.0          1.0
2  30.0  55000.0           0.0         1.0          0.0
3  35.0  57500.0           1.0         0.0          0.0
4  40.0  65000.0           0.0         1.0          0.0


In [27]:
from sklearn.compose import ColumnTransformer

num_cols = ["Age", "Salary"]
cat_cols = ["City"]

preprocessor = ColumnTransformer([
    ("num", SimpleImputer(strategy="mean"), num_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
])

df_processed = preprocessor.fit_transform(df)

print(df_processed)

[[2.50e+01 5.00e+04 0.00e+00 1.00e+00 0.00e+00]
 [3.25e+01 6.00e+04 0.00e+00 0.00e+00 1.00e+00]
 [3.00e+01 5.50e+04 0.00e+00 1.00e+00 0.00e+00]
 [3.50e+01 5.75e+04 1.00e+00 0.00e+00 0.00e+00]
 [4.00e+01 6.50e+04 0.00e+00 1.00e+00 0.00e+00]]
